name: flutter_template
version: "0.0.1-dev.0"
description: a Flutter template project for development.
publish_to: none

dependencies:
  auto_route: 5.0.1
  dio: 4.0.6
  elementary: 1.5.0
  firebase_crashlytics: 3.0.12
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  logger: 1.1.0
  path_provider: 2.0.11
  provider: 6.0.3
  shared_preferences: 2.0.15
  surf_logger: 1.1.0

dev_dependencies:
  auto_route_generator: 5.0.2
  json_serializable: 6.3.2
  retrofit_generator: 4.0.3+2
  surf_lint_rules: 1.5.0

environment:
  sdk: ">=2.17.0-0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
