name: "Label issues"

on:
  issues:
    types:
      - labeled

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "new issues"
          repo-token: ${{ secrets.SECRET_ISSUES }}
