# Проверка на соответствие шаблону при запросе ревью
# Установка лейбла из готового файла

name: "Pull request check"
on:
  pull_request:
    types: [opened]

jobs:
  pull_request_check_template:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check Related tasks
        if: ${{ contains(github.event.pull_request.body, 'Related tasks') }}
        run: echo "Related tasks"
      - name: Changes
        if: ${{ contains(github.event.pull_request.body, 'Changes') }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('No Changes find!')
